// src/routes/work/+page.svelte
<script lang="ts">
	import StaticImage from '$lib/components/StaticImage.svelte';
</script>

<div class="relative min-h-screen">
	<div class="relative z-10 mx-auto flex min-h-screen w-full max-w-[66rem] items-center px-6 py-24 sm:px-12 xl:px-12">
		<div class="flex w-full flex-col gap-6 md:gap-10">
			<nav aria-label="breadcrumb" class="hidden md:flex">
				<ol class="flex flex-wrap items-center gap-2 text-sm">
					<li class="inline-flex items-center gap-2 transition-colors hover:text-primary">
						<a href="/" class="transition-colors hover:text-primary">home</a>
					</li>
					<li class="text-muted-foreground">/</li>
					<li class="inline-flex items-center gap-2 transition-colors">
						<span class="text-foreground">work</span>
					</li>
				</ol>
			</nav>

			<div class="flex flex-col gap-8 w-full">
				<h1 class="text-3xl font-bold tracking-tight">work</h1>

				<div class="flex flex-col gap-6">
					<div class="flex flex-row gap-4 items-center rounded-md border border-border/70 bg-card p-4">
						<div class="relative h-14 w-14 flex-shrink-0">
							<StaticImage
								alt="Mouts TI logo"
								src="/assets/mouts_logo.jpg"
								class="rounded-md object-cover transition-transform duration-300 hover:scale-110"
							/>
						</div>
						<div class="flex flex-col w-full min-w-0">
							<div class="flex flex-row gap-4 justify-between items-baseline w-full">
								<div class="font-semibold text-base sm:text-lg truncate">Junior Software Developer</div>
								<div class="hidden sm:flex text-muted-foreground text-sm flex-shrink-0">Aug 2024 - Present</div>
							</div>
							<div class="text-muted-foreground text-sm">Mouts TI</div>
							<div class="sm:hidden text-muted-foreground text-xs">Aug 2024 - Present</div>
						</div>
					</div>
				</div>
			</div>

			<div class="flex flex-col gap-8 w-full">
				<h1 class="text-3xl font-bold tracking-tight">education</h1>

				<div class="flex flex-col gap-6">
					<div class="flex flex-row gap-4 items-center rounded-md border border-border/70 bg-card p-4">
						<div class="relative h-14 w-14 flex-shrink-0 overflow-hidden rounded-md bg-white p-1.5">
							<StaticImage
								alt="IFC logo"
								src="/assets/ifc_logo.png"
								class="transition-transform duration-300 hover:scale-110 object-contain h-full w-full"
							/>
						</div>
						<div class="flex flex-col w-full min-w-0">
							<div class="flex flex-row gap-4 justify-between items-baseline w-full">
								<div class="font-semibold text-base sm:text-lg truncate">
									Bachelor&apos;s in Computer Science
								</div>
								<div class="hidden sm:flex text-muted-foreground text-sm flex-shrink-0">
									Jan 2023 - Dec 2026
								</div>
							</div>
							<div class="text-muted-foreground text-sm">
								Catarinense Federal Institute (IFC)
							</div>
							<div class="sm:hidden text-muted-foreground text-xs">
								Jan 2023 - Dec 2026
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

// app/work/page.tsx
import Link from "next/link";
import Image from "next/image";

export default function WorkPage() {
  return (
    <div className="flex min-h-screen flex-col justify-center items-center p-8 md:p-24">
      <div className="flex flex-col gap-4 md:gap-12 max-w-3xl w-full">
        <nav aria-label="breadcrumb" className="hidden md:flex">
          <ol className="flex flex-wrap items-center gap-1.5 break-words text-sm sm:gap-2.5">
            <li className="inline-flex items-center gap-1.5 transition ease-in-out hover:scale-110">
              <Link href="/" className="transition-colors hover:text-primary">
                home
              </Link>
            </li>
            <li className="text-muted-foreground text-lg">/</li>
            <li className="inline-flex items-center gap-1.5 transition ease-in-out hover:scale-110">
              <Link href="/work" className="transition-colors text-muted-foreground hover:text-primary">
                work
              </Link>
            </li>
          </ol>
        </nav>

        <div className="flex flex-col gap-6 md:gap-10 w-full">
          <div className="flex flex-col gap-5">
            <h1 className="text-3xl font-bold">work</h1>

            <div className="flex flex-col gap-4">
              <div className="flex flex-col gap-4">
                <div className="flex flex-row gap-4 items-center">
                  <div className="relative h-12 aspect-square">
                    <Image
                      alt="Mouts TI logo"
                      src="/assets/mouts_logo.jpg"
                      fill
                      className="border shadow-sm transition hover:scale-110 ease-in-out object-cover"
                    />
                  </div>
                  <div className="flex flex-col w-full">
                    <div className="flex flex-row gap-4 justify-between items-baseline w-full">
                      <div className="font-semibold sm:text-lg">
                        Junior Software Developer
                      </div>
                      <div className="hidden sm:flex text-muted-foreground">
                        Aug 2024 - Present
                      </div>
                    </div>
                    <div className="text-muted-foreground text-sm sm:text-base">
                      Mouts TI
                    </div>
                    <div className="sm:hidden text-muted-foreground text-xs">
                      Aug 2024 - Present
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <div className="flex flex-col gap-5">
            <h1 className="text-3xl font-bold">education</h1>

            <div className="flex flex-col gap-4">
              <div className="flex flex-col gap-4">
                <div className="flex flex-row gap-4 items-center">
                  <div className="relative h-12 aspect-square bg-white border p-2">
                    <Image
                      alt="IFC logo"
                      src="/assets/ifc_logo.png"
                      fill
                      className="transition hover:scale-110 ease-in-out object-contain"
                    />
                  </div>
                  <div className="flex flex-col w-full">
                    <div className="flex flex-row gap-4 justify-between items-baseline w-full">
                      <div className="font-semibold sm:text-lg">
                        Bachelor&apos;s in Computer Science
                      </div>
                      <div className="hidden sm:flex text-muted-foreground">
                        Jan 2023 - Dec 2026 (expected)
                      </div>
                    </div>
                    <div className="text-muted-foreground text-sm sm:text-base">
                      Catarinense Federal Institute (IFC)
                    </div>
                    <div className="sm:hidden text-muted-foreground text-xs">
                      Jan 2023 - Dec 2026
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
