// components/navbar.tsx
"use client";

import * as React from "react";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { cn } from "@/lib/utils";

const navItems = [
  { href: "/", label: "Home" },
  { href: "/work", label: "Work" },
  { href: "/projects", label: "Projects" },
];

export function Navbar() {
  const pathname = usePathname();

  return (
    <div className="flex items-center gap-6">
      <div className="hidden md:flex md:items-center md:space-x-6">
        {navItems.map((item) => (
          <Link
            key={item.href}
            href={item.href}
            className={cn(
              "text-sm font-medium transition-colors hover:text-primary",
              pathname === item.href
                ? "text-foreground"
                : "text-muted-foreground"
            )}
          >
            {item.label}
          </Link>
        ))}
      </div>
    </div>
  );
}

// src/lib/components/Navbar.svelte
<script lang="ts">
	import { cn } from '$lib/utils';

	interface Props {
		navItems: Array<{ href: string; label: string }>;
		isActive: (href: string, currentPath: string) => boolean;
		pathname: string;
	}

	let { navItems, isActive, pathname }: Props = $props();
</script>

<div class="flex items-center gap-6">
	<div class="hidden md:flex md:items-center md:space-x-6">
		{#each navItems as item}
			<a
				href={item.href}
				class={cn(
					'text-sm font-medium transition-colors hover:text-primary',
					isActive(item.href, pathname)
						? 'text-foreground'
						: 'text-muted-foreground'
				)}
			>
				{item.label}
			</a>
		{/each}
	</div>
</div>
